### ISSUE TITLE
can't resume if auich is used

### ISSUE THREAD

**Issue by ghost** [elad/gnats-nb#740]
### Metadata
- Number: [24872](http://gnats.netbsd.org/24872)
- Originator: Kazu Yamamoto &lt;[kazu@iijlab.net](mailto:kazu@iijlab.net)&gt;
- Arrived: Mon Mar 22 04:41:00 +0000 2004
- Last modified: Sun Nov 15 01:03:30 +0000 2009
- Environment: NetBSD caster.iij.ad.jp 1.6ZK NetBSD 1.6ZK (GENERIC_LAPTOP) #0: Wed Mar 17 15:12:30 JST 2004  kazu@caster.iij.ad.jp:/usr/src/sys/arch/i386/compile/GENERIC_LAPTOP i386
### Description

```

I'm using ThinkPad X30 + NetBSD 1.6ZK + XFree 86 ver 4.4.0.

If I use windowmaker as a window manager, NetBSD can suspend/resume.

However, if I use Gnome installed with pkgsrc, NetBSD cannot resume correctly. It can suspend, and when I open my laptop, it displays
Gnome but no keyboard/mouse events are accepted.

The same problem occurs when I use windowmaker and executes xine. If xine
is running (playing nothing, just xine window is displayed), NetBSD cannot
resume correctly.

```
### How to repeat

```

Install gnome onto a laptop. And close the laptop to suspend NetBSD.
Then open the laptp to resume NetBSD.

```
### Audit trail

```

From: Kazu Yamamoto (=?iso-2022-jp?B?GyRCOzNLXE9CSScbKEI=?=) <kazu@iijlab.net>
To: gnats-bugs@NetBSD.org
Cc: 
Subject: Re: pkg/24872
Date: Wed, 10 Nov 2004 22:13:01 +0900 (JST)

 It appears that this is the same problem as:
    http://mail-index.netbsd.org/port-i386/2004/03/16/0005.html

 Removing the volume control, ThinkPad can resume with Gnome.

 Thus, I guess this is a bug of the driver for /dev/mixer0.

 dmesg says as follows:

 auich0 at pci0 dev 31 function 5: i82801CA (ICH3) AC-97 Audio
 auich0: interrupting at irq 11
 auich0: ac97: Analog Devices AD1981A codec; headphone, 20 bit DAC, no 3D stereo
 auich0: ac97: ext id 601<AC97_22,AMAP,VRA>

 --Kazu Yamamoto
Responsible-Changed-From-To: pkg-manager->kern-bug-people
Responsible-Changed-By: wiz@netbsd.org
Responsible-Changed-When: Tue, 15 Mar 2005 16:14:57 +0000
Responsible-Changed-Why:
kernel bug (auich)


State-Changed-From-To: open->feedback
State-Changed-By: jmcneill@NetBSD.org
State-Changed-When: Wed, 24 Dec 2008 19:07:13 +0000
State-Changed-Why:
Is this still an issue?


State-Changed-From-To: feedback->open
State-Changed-By: dholland@NetBSD.org
State-Changed-When: Sun, 15 Nov 2009 01:03:30 +0000
State-Changed-Why:
Feedback timeout. Anyone know the state of suspend/resume wrt auich(4)?



```
